// resalt-frontend2/src/components/CopyButton.tsx
import { Button, Tooltip, tokens } from '@fluentui/react-components';
import { ClipboardLinkFilled, ClipboardLinkRegular, bundleIcon } from '@fluentui/react-icons';
import { ToastController } from '../lib/toast';

const CopyIcon = bundleIcon(ClipboardLinkFilled, ClipboardLinkRegular);

export function CopyButton(props: {
	name: string;
	value: string;
	toastController: ToastController;
}) {
	const copy = () => {
		if (!props.value) {
			props.toastController.warning(`Nothing to copy`, `No value for "${props.name}'`);
		}
		navigator.clipboard.writeText(props.value + '');
		props.toastController.success(`Copied ${props.name}`);
	};
	return (
		<Tooltip content="Copy" relationship="label">
			<Button
				appearance="subtle"
				size="small"
				icon={<CopyIcon />}
				onClick={copy}
				style={{ marginLeft: tokens.spacingHorizontalXS }}
			/>
		</Tooltip>
	);
}

// frontend/src/components/CopyButton.svelte
<script lang="ts">
	import Icon from '../components/Icon.svelte';
	import { toasts } from '$lib/stores';
	import { MessageType } from '../models/MessageType';
	import { theme } from '$lib/stores';

	export let name: string;
	export let value: string;
</script>

<button
	class="btn btn-{$theme.color} btn-sm ms-2"
	style="margin-bottom: -0.15rem;margin-top: -0.15rem;"
	on:click={() => {
		navigator.clipboard.writeText(value);
		toasts.add(
			MessageType.SUCCESS,
			'Copied to Clipboard',
			`Copied ${name} "${value}" to clipboard.`,
		);
	}}
>
	<Icon name="clipboard" size="1" align="top" style="padding-top: 0.15rem;" />
</button>
